# COOLDOWNS
SKILL_COOLDOWN = 3100
DRAG_COOLDOWN = 260
USE_COOLDOWN = 3250
MINING_COOLDOWN = 4200
BANDAGE_COOLDOWN = 8000

# WEIGHTS
WEIGHT_ORE = 12
WEIGHT_LOGS = 2
WEIGHT_INGOT = 1

# COLORS
COLOR_INGOT_IRON = 0x0961
COLOR_ORE_IRON = 0x0000
COLOR_LOGS_S = 0x0000

# COORDS
COORDS_MINOC_HEALER = (2572, 585)

# TYPE IDS
TYPE_ID_BANDAGE = 0x0E21
TYPE_ID_ORE = 0x19B9
TYPE_ID_INGOT = 0x1BF2
TYPE_ID_LOGS = 0x1BE0
TYPE_ID_FORGE = 0x0FB1
TYPE_ID_FOOD_FISHSTEAKS = 0x097B

TYPE_ID_TOOL_FISHING_POLE = 3519
TYPE_ID_TOOL_PICKAXE = 0x0E85
TYPE_IDS_TOOL = [
    TYPE_ID_TOOL_FISHING_POLE,
    TYPE_ID_TOOL_PICKAXE,
]

TYPE_ID_KATANA = 0x13FF
TYPE_ID_HATCHET = 0x0F43
TYPE_ID_SHIELD_KITE = 0x1B74

TYPE_ID_FEATHERS = 0x1BD1
TYPE_ID_REAGENT_SA = 0x0F8C
TYPE_ID_REAGENT_BP = 0x0F7A
TYPE_ID_REAGENT_GI = 0x0F85
TYPE_ID_REAGENT_BM = 0x0F7B
TYPE_ID_REAGENT_SS = 0x0F8D
TYPE_ID_REAGENT_NS = 0x0F88
TYPE_ID_REAGENT_GA = 0x0F84
TYPE_ID_REAGENT_MR = 0x0F86
TYPE_IDS_REAGENT = [
    TYPE_ID_REAGENT_SA,
    TYPE_ID_REAGENT_BP,
    TYPE_ID_REAGENT_GI,
    TYPE_ID_REAGENT_BM,
    TYPE_ID_REAGENT_SS,
    TYPE_ID_REAGENT_NS,
    TYPE_ID_REAGENT_GA,
    TYPE_ID_REAGENT_MR,
]

TYPE_ID_GOLD = 0x0EED

TYPE_ID_ARROWS = 0x0F3F

TYPE_IDS_LOOT = [
    TYPE_ID_GOLD,
    TYPE_ID_FEATHERS,
    TYPE_ID_ARROWS,
    *TYPE_IDS_REAGENT,
]

TYPE_IDS_MINING_LOOT = [
    *TYPE_IDS_LOOT,
    TYPE_ID_INGOT,
    TYPE_ID_ORE,
    TYPE_ID_BANDAGE,
    TYPE_ID_TOOL_PICKAXE,
]

TYPE_IDS_LJ_LOOT = [
    *TYPE_IDS_LOOT,
    TYPE_ID_BANDAGE,
    TYPE_ID_HATCHET,
    TYPE_ID_LOGS,
]

# MOBS
TYPE_ID_MOB_REAPER = 0x002F

TYPE_IDS_MOBS = [
    TYPE_ID_MOB_REAPER,
]
