from enum import Enum, unique
from .constants_weapons import *
from .constants_armor import *
from .constants_creatures import *
from .constants_scrolls import *
from .constants_gems import *
from .constants_reagents import *
from .constants_food import *
from .constants_colors import *


@unique
class Notoriety(Enum):
    Unknown = 0x00
    Innocent = 0x01
    Ally = 0x02
    Gray = 0x03
    Criminal = 0x04
    Enemy = 0x05
    Murderer = 0x06
    Invulnerable = 0x07
    Player = 65


# RANGES
AGGRO_RANGE = 15
ENGAGE_MAX_DISTANCE = 25
USE_GROUND_RANGE = 3
MAX_PICK_UP_DISTANCE = 3

# COOLDOWNS
SKILL_COOLDOWN = 3100
DRAG_COOLDOWN = 260
USE_COOLDOWN = 3250
MINING_COOLDOWN = 4200
BANDAGE_COOLDOWN = 8000
LOOT_COOLDOWN = 650

# WEIGHTS
WEIGHT_ORE = 12
WEIGHT_LOGS = 2
WEIGHT_INGOT = 1

# COORDS
COORDS_MINOC_HEALER = (2572, 585)
COORDS_MINOC_BANK = (2512, 556)

# TYPE IDS
TYPE_ID_CORPSE = 0x2006
TYPE_ID_HIDE = 0x1078
TYPE_ID_FEATHERS = 0x1BD1

# TILES
TYPE_ID_TILE_FISHING = [
    0x179A,
    0x179B,
    0x179C,
    0x1797,
    0x1799,
]

# FISH
TYPE_ID_FISH = [
    0x09CE,
    0x09CD,
    0x09CC,
]
TYPE_IDS_FISH_TRASH = [
    0x1AE1,
    0x1AE2,
    0x1AE4,
    0x1EA3,
    0x1EA5,
    0x0F7A,  # painting
    0x0EC8,
    0x0FC4,
    0x0FC7,
    0x0FC8,
    TYPE_ID_SHIELD_BRONZE,
]

# CRAFT
TYPE_ID_BANDAGE = 0x0E21
TYPE_ID_ORE = 0x19B9
TYPE_ID_INGOT = 0x1BF2
TYPE_ID_LOGS = 0x1BE0
TYPE_ID_FORGE = 0x0FB1

# TOOLS
TYPE_ID_TOOL_FISHING_POLE = 3519
TYPE_ID_TOOL_PICKAXE = 0x0E85
TYPE_IDS_TOOL = [
    TYPE_ID_TOOL_FISHING_POLE,
    TYPE_ID_TOOL_PICKAXE,
]


# TREASURES
TYPE_ID_GOLD = 0x0EED
TYPE_ID_TREASURE_MAP = 0x14EB
TYPE_ID_EMPTY_MAP = 0x14ED
TYPE_ID_BIG_CHEST_1 = 0x0E40
TYPE_ID_BIG_CHEST_3 = 0x0E43


# AMMO
TYPE_ID_ARROWS = 0x0F3F
TYPE_ID_BOLTS = 0x1BFB


# LOOT
TYPE_IDS_LOOT = [
    TYPE_ID_GOLD,
    TYPE_ID_FEATHERS,
    TYPE_ID_ARROWS,
    TYPE_ID_BOLTS,
    TYPE_ID_VIAL_OF_BLOOD,
    TYPE_ID_EYE_OF_NEWT,
    TYPE_ID_TREASURE_MAP,
    TYPE_ID_BIG_CHEST_1,
    TYPE_ID_BIG_CHEST_3,
    TYPE_ID_EMPTY_MAP,
    *TYPE_IDS_WEAPONS,
    *TYPE_IDS_ARMOR,
    *TYPE_IDS_REAGENT,
]

TYPE_IDS_MINING_LOOT = [
    *TYPE_IDS_LOOT,
    TYPE_ID_INGOT,
    TYPE_ID_ORE,
    TYPE_ID_BANDAGE,
    TYPE_ID_TOOL_PICKAXE,
    TYPE_ID_HIDE,
    TYPE_ID_HATCHET,  # mobs occasionaly drop hatchets
    TYPE_ID_SCEPTER,
    TYPE_ID_WAND,
]

TYPE_IDS_LJ_LOOT = [
    *TYPE_IDS_LOOT,
    # TYPE_ID_BANDAGE,
    # TYPE_ID_HATCHET,
    TYPE_ID_LOGS,
    TYPE_ID_HIDE,
]

ITEM_IDS_TRASH = [
    *TYPE_ID_GEMS,
    *TYPE_IDS_RAW_FOOD,
]

ITEM_IDS_MINING_TRASH = [
    *ITEM_IDS_TRASH,
    *TYPE_IDS_ARMOR_BONE,
    TYPE_ID_SHIELD_WOODEN,
    TYPE_ID_HELMET,
    TYPE_ID_SKINNING_KNIFE,
    TYPE_ID_MEAT_CLEAVER,
    TYPE_ID_BUTCHER_KNIFE,
    TYPE_ID_SCIMITAR,
    TYPE_ID_PLATE_GLOVES,
    TYPE_ID_PLATE_SLEEVES,
    *TYPE_ID_STAFFS,
    TYPE_ID_MACE,
    TYPE_ID_DAGGER,
    *TYPE_ID_SCROLLS,
]
TYPE_IDS_MINING_LOOT = [i for i in TYPE_IDS_MINING_LOOT if i not in ITEM_IDS_MINING_TRASH]


if __name__ == '__main__':
    pass
