# MOBS
TYPE_ID_MALE = 0x0190
TYPE_ID_FEMALE = 0x0191
TYPE_IDS_HUMAN = [
    TYPE_ID_MALE,
    TYPE_ID_FEMALE,
]

TYPE_ID_POISON_ELEM = 0x000D
TYPE_ID_MOB_REAPER = 0x002F
TYPE_ID_MOB_ETIN = 0x0012
TYPE_ID_MOB_SWAMP_TENTACLE = 0x0008
TYPE_ID_MOB_FOREST_SPIDER = 0x001C
TYPE_ID_GIANT_SERPENT = 0x0015
TYPE_ID_SEA_SERPENT = 0x0096
TYPE_ID_MONGBAT = 0x0027
TYPE_ID_HARPY = 0x001E
TYPE_ID_OGRE = 0x0001
TYPE_ID_BLOOD_ELEM = 0x0010
TYPE_ID_BONE_MAGI = 0x0032

TYPE_IDS_MOB = [
    TYPE_ID_POISON_ELEM,
    TYPE_ID_MOB_REAPER,
    TYPE_ID_MOB_ETIN,
    TYPE_ID_MOB_SWAMP_TENTACLE,
    TYPE_ID_MOB_FOREST_SPIDER,
    TYPE_ID_GIANT_SERPENT,
    TYPE_ID_SEA_SERPENT,
    TYPE_ID_MONGBAT,
    TYPE_ID_HARPY,
    TYPE_ID_OGRE,
    TYPE_ID_BLOOD_ELEM,
    TYPE_ID_BONE_MAGI,
]

TYPE_IDS_CREATURE = [
    *TYPE_IDS_HUMAN,
    *TYPE_IDS_MOB,
]


TYPE_IDS_MOB_AGGRESSIVE = [
    TYPE_ID_MOB_REAPER,
    TYPE_ID_MOB_ETIN,
    TYPE_ID_MOB_SWAMP_TENTACLE,
    TYPE_ID_MOB_FOREST_SPIDER,
    TYPE_ID_GIANT_SERPENT,
    TYPE_ID_MONGBAT,
    TYPE_ID_HARPY,
    TYPE_ID_OGRE,
    TYPE_ID_BLOOD_ELEM,
    TYPE_ID_SEA_SERPENT,
    TYPE_ID_POISON_ELEM,
    TYPE_ID_BONE_MAGI,
]
TYPE_IDS_MOB_MELEE = [
    TYPE_ID_MOB_SWAMP_TENTACLE,
    TYPE_ID_MOB_FOREST_SPIDER,
    TYPE_ID_GIANT_SERPENT,
    TYPE_ID_MONGBAT,
    TYPE_ID_HARPY,
    TYPE_ID_OGRE,
    TYPE_ID_BLOOD_ELEM,
]
TYPE_IDS_MOB_RANGED = [
    TYPE_ID_MOB_REAPER,
    TYPE_ID_MOB_ETIN,
    TYPE_ID_BLOOD_ELEM,
    TYPE_ID_SEA_SERPENT,
    TYPE_ID_POISON_ELEM,
    TYPE_ID_BONE_MAGI,
]

TYPE_ID_EAGLE = 0x0005
TYPE_ID_GREY_WOLF = 0x00E1
TYPE_ID_PANTHER = 0x00D6
TYPE_ID_RABBIT = 0x00CD
TYPE_ID_BLACK_BEAR = 0x00D3
TYPE_ID_WOODPECKER = 0x0006
TYPE_ID_GREAT_HART = 0x00EA
TYPE_ID_HORSE = 0x00E4
TYPE_ID_BLUE_BIRD = 0x0006

# MOUNTS
TYPE_ID_MOUNT_NIGHTMARE = 0x00E2
TYPE_IDS_MOUNT = [
    TYPE_ID_MOUNT_NIGHTMARE,
]
NAMES_MOUNT = [
    'a drake',
]
TYPE_IDS_CRITTER = [
    TYPE_ID_EAGLE,
    TYPE_ID_GREY_WOLF,
    TYPE_ID_PANTHER,
    TYPE_ID_RABBIT,
    TYPE_ID_BLACK_BEAR,
    TYPE_ID_WOODPECKER,
    TYPE_ID_GREAT_HART,
    TYPE_ID_HORSE,
    TYPE_ID_BLUE_BIRD,
]