# ARMOR
TYPE_ID_HELMET = 0x140A

TYPE_ID_CHAIN_COLF = 0x13BB

TYPE_ID_PLATE_GORGET = 0x1413
TYPE_ID_PLATEMAIL = 0x1416
TYPE_ID_PLATE_GLOVES = 0x1414
TYPE_ID_PLATE_SLEEVES = 0x1410

TYPE_ID_BONE_GLOVES = 0x1450
TYPE_ID_BONE_ARMS = 0x144E
TYPE_ID_BONE_CHEST = 0x144F
TYPE_ID_BONE_LEGS = 0x1452
TYPE_ID_BONE_HELM = 0x1451

TYPE_IDS_ARMOR_BONE = [
    TYPE_ID_BONE_GLOVES,
    TYPE_ID_BONE_ARMS,
    TYPE_ID_BONE_CHEST,
    TYPE_ID_BONE_LEGS,
    TYPE_ID_BONE_HELM,
]
TYPE_IDS_ARMOR_PLATE = [
    TYPE_ID_PLATE_GORGET,
    TYPE_ID_PLATEMAIL,
    TYPE_ID_PLATE_GLOVES,
    TYPE_ID_PLATE_SLEEVES,
]
TYPE_IDS_ARMOR_CHAIN = [
    TYPE_ID_CHAIN_COLF,
]
TYPE_IDS_ARMOR = [
    TYPE_ID_HELMET,
    *TYPE_IDS_ARMOR_CHAIN,
    *TYPE_IDS_ARMOR_PLATE,
    *TYPE_IDS_ARMOR_BONE,
]