# WEAPONS
TYPE_ID_KRYSS = 0x1400
TYPE_ID_KATANA = 0x13FF
TYPE_ID_HATCHET = 0x0F43
TYPE_ID_MACE = 0x0F5C
TYPE_ID_WARMACE = 0x1406
TYPE_ID_MAUL = 0x0F5C
TYPE_ID_CUTLASS = 0x1440
TYPE_ID_BATTLE_AXE = 0x0F47
TYPE_ID_AXE = 0x0F49
TYPE_ID_DOUBLE_AXE = 0x0F4B
TYPE_ID_HALBERT = 0x143E
TYPE_ID_CLUB = 0x13B4
TYPE_ID_DAGGER = 0x0F51
TYPE_ID_SCEPTER = 0x0DF2
TYPE_ID_WAND = 0x0DF5
TYPE_ID_SCIMITAR = 0x13B6
TYPE_ID_BROAD_SWORD = 0x0F5E
TYPE_ID_BUTCHER_KNIFE = 0x13F7
TYPE_ID_MEAT_CLEAVER = 0x0EC2
TYPE_ID_SKINNING_KNIFE = 0x0EC4
TYPE_ID_PITCHFORK = 0x0E87
TYPE_ID_HAMMER_PICK = 0x143C
TYPE_ID_WAR_AXE = 0x13B0
TYPE_ID_EXECUTIONER_AXE = 0x0F45
TYPE_ID_VIKING_SWORD = 0x13BA
TYPE_ID_WAR_HAMMER = 0x1438
TYPE_ID_SPEAR = 0x0F62

TYPE_ID_STAFF_QUARTER = 0x0E8A
TYPE_ID_STAFF_BLACK = 0x0DF0
TYPE_ID_STAFF_GNARLED = 0x13F9
TYPE_ID_STAFFS = [
    TYPE_ID_STAFF_QUARTER,
    TYPE_ID_STAFF_BLACK,
    TYPE_ID_STAFF_GNARLED,
]

TYPE_ID_CROSSBOW = 0x0F4F

TYPE_IDS_MELEE_WEAPONS = [
    TYPE_ID_KRYSS,
    TYPE_ID_KATANA,
    TYPE_ID_VIKING_SWORD,
    TYPE_ID_MACE,
    TYPE_ID_WARMACE,
    TYPE_ID_CUTLASS,
    TYPE_ID_AXE,
    TYPE_ID_BATTLE_AXE,
    TYPE_ID_DOUBLE_AXE,
    TYPE_ID_HALBERT,
    TYPE_ID_CLUB,
    TYPE_ID_MAUL,
    TYPE_ID_DAGGER,
    TYPE_ID_SCEPTER,
    TYPE_ID_WAND,
    TYPE_ID_SCIMITAR,
    # TYPE_ID_HATCHET,
    TYPE_ID_BUTCHER_KNIFE,
    TYPE_ID_MEAT_CLEAVER,
    TYPE_ID_SKINNING_KNIFE,
    TYPE_ID_PITCHFORK,
    TYPE_ID_HAMMER_PICK,
    TYPE_ID_BROAD_SWORD,
    TYPE_ID_WAR_AXE,
    TYPE_ID_EXECUTIONER_AXE,
    TYPE_ID_WAR_HAMMER,
    TYPE_ID_SPEAR,
    *TYPE_ID_STAFFS,
]

TYPE_IDS_RANGED_WEAPONS = [
    TYPE_ID_CROSSBOW,
]
TYPE_IDS_WEAPONS = [
    *TYPE_IDS_MELEE_WEAPONS,
    *TYPE_IDS_RANGED_WEAPONS,
]

TYPE_IDS_CORPSE_CUT_TOOLS = [  # todo: fill up
    TYPE_ID_SKINNING_KNIFE,
    TYPE_ID_MEAT_CLEAVER,
    TYPE_ID_DAGGER,
    TYPE_ID_BUTCHER_KNIFE,
    TYPE_ID_CUTLASS,
    TYPE_ID_SCIMITAR,
    TYPE_ID_BROAD_SWORD,
    TYPE_ID_HATCHET,
    TYPE_ID_WAR_AXE,
    TYPE_ID_BATTLE_AXE,
    TYPE_ID_DOUBLE_AXE,
    TYPE_ID_EXECUTIONER_AXE,
    TYPE_ID_KATANA,
    TYPE_ID_KRYSS,
    TYPE_ID_VIKING_SWORD,
    TYPE_ID_HALBERT,
]

TYPE_ID_SHIELD_KITE = 0x1B74
TYPE_ID_SHIELD_BRONZE = 0x1B72
TYPE_ID_SHIELD_WOODEN = 0x1B7A

TYPE_IDS_SHIELDS = [
    TYPE_ID_SHIELD_KITE,
    TYPE_ID_SHIELD_BRONZE,
    TYPE_ID_SHIELD_WOODEN,
]