# RESOURCES
TYPE_ID_ORE = 0x19B9
TYPE_ID_INGOT = 0x1BF2
TYPE_ID_LOGS = 0x1BE0
TYPE_ID_HIDE = 0x1078
TYPE_ID_FEATHERS = 0x1BD1

TYPE_IDS_RESOURCES = [
    TYPE_ID_ORE,
    TYPE_ID_INGOT,
    TYPE_ID_LOGS,
    TYPE_ID_HIDE,
    TYPE_ID_FEATHERS,
]
