# FOOD
TYPE_ID_RAW_RIBS = 0x09F1
TYPE_ID_RAW_LEG_OF_LAMB = 0x1609
TYPE_ID_RAW_BIRD = 0x09B9
TYPE_ID_RAW_FISHSTEAKS = 0x097A

TYPE_ID_FOOD_FISHSTEAKS = 0x097B

TYPE_IDS_RAW_FOOD = [
    TYPE_ID_RAW_RIBS,
    TYPE_ID_RAW_LEG_OF_LAMB,
    TYPE_ID_RAW_BIRD,
    TYPE_ID_RAW_FISHSTEAKS,
]