# WEAPONS
TYPE_ID_KRYSS = 0x1400
TYPE_ID_KATANA = 0x13FF
TYPE_ID_HATCHET = 0x0F43
TYPE_ID_SHIELD_KITE = 0x1B74
TYPE_ID_SHIELD_BRONZE = 0x1B72
TYPE_ID_SHIELD_WOODEN = 0x1B7A
TYPE_ID_MACE = 0x0F5C
TYPE_ID_MAUL = 0x0F5C
TYPE_ID_CUTLASS = 0x1440
TYPE_ID_BATTLE_AXE = 0x0F47
TYPE_ID_AXE = 0x0F49
TYPE_ID_HALBERT = 0x143E
TYPE_ID_CROSSBOW = 0x0F4F
TYPE_ID_CLUB = 0x13B4
TYPE_ID_DAGGER = 0x0F51
TYPE_ID_SCEPTER = 0x0DF2
TYPE_ID_WAND = 0x0DF5
TYPE_ID_SCIMITAR = 0x13B6
TYPE_ID_BUTCHER_KNIFE = 0x13F7
TYPE_ID_MEAT_CLEAVER = 0x0EC2
TYPE_ID_SKINNING_KNIFE = 0x0EC4

TYPE_ID_STAFF_QUARTER = 0x0E8A
TYPE_ID_STAFF_BLACK = 0x0DF0
TYPE_ID_STAFF_GNARLED = 0x13F9
TYPE_ID_STAFFS = [
    TYPE_ID_STAFF_QUARTER,
    TYPE_ID_STAFF_BLACK,
    TYPE_ID_STAFF_GNARLED,
]

TYPE_IDS_WEAPONS = [
    TYPE_ID_KRYSS,
    TYPE_ID_KATANA,
    TYPE_ID_MACE,
    TYPE_ID_CUTLASS,
    TYPE_ID_AXE,
    TYPE_ID_BATTLE_AXE,
    TYPE_ID_HALBERT,
    TYPE_ID_CLUB,
    TYPE_ID_MAUL,
    TYPE_ID_DAGGER,
    TYPE_ID_SCEPTER,
    TYPE_ID_WAND,
    TYPE_ID_SCIMITAR,
    # TYPE_ID_HATCHET,
    TYPE_ID_BUTCHER_KNIFE,
    TYPE_ID_MEAT_CLEAVER,
    TYPE_ID_SKINNING_KNIFE,
    *TYPE_ID_STAFFS,
]
TYPE_IDS_CORPSE_CUT_TOOLS = [  # todo: fill up
    TYPE_ID_HATCHET,
    TYPE_ID_BATTLE_AXE,
    TYPE_ID_CUTLASS,
    TYPE_ID_SCIMITAR,
    TYPE_ID_KATANA,
    TYPE_ID_KRYSS,
    TYPE_ID_HALBERT,
    TYPE_ID_DAGGER,
    TYPE_ID_BUTCHER_KNIFE,
    TYPE_ID_MEAT_CLEAVER,
    TYPE_ID_SKINNING_KNIFE,
]