from py_stealth import *

# REAGENTS
TYPE_ID_REAGENT_SA = SA()
TYPE_ID_REAGENT_BP = BP()
TYPE_ID_REAGENT_GI = GS()
TYPE_ID_REAGENT_BM = BM()
TYPE_ID_REAGENT_SS = SS()
TYPE_ID_REAGENT_NS = NS()
TYPE_ID_REAGENT_GA = GA()
TYPE_ID_REAGENT_MR = MR()
TYPE_ID_VIAL_OF_BLOOD = 0x0F7D
TYPE_ID_EYE_OF_NEWT = 0x0F87
TYPE_ID_DEAD_WOOD = 0x0F90

TYPE_IDS_MAGIC_REAGENT = [
    TYPE_ID_REAGENT_SA,
    TYPE_ID_REAGENT_BP,
    TYPE_ID_REAGENT_GI,
    TYPE_ID_REAGENT_BM,
    TYPE_ID_REAGENT_SS,
    TYPE_ID_REAGENT_NS,
    TYPE_ID_REAGENT_GA,
    TYPE_ID_REAGENT_MR,
]

TYPE_IDS_REAGENT = [
    *TYPE_IDS_MAGIC_REAGENT,
    TYPE_ID_VIAL_OF_BLOOD,
    TYPE_ID_EYE_OF_NEWT,
    TYPE_ID_DEAD_WOOD,
]
